method: random
name: tune_ts
metric:
    goal: minimize
    name: val_loss
    
parameters:
    epochs:
        value: 100
    val_interval:
        value: 1
    save_interval:
        value: 50
    num_workers: 
        value: 8
    batch_size:
        values: [2, 4, 8, 16, 32]
    lr:
        max: 0.001
        min: 0.00001
    weight_decay:
        max: 0.0001
        min: 0.00001
    num_features:
        [3, 5, 6, 8, 10, 20, 30, 50]
        
